import { Category, Recipe, Product, Review, UserProfile } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
    {
        id: 'cat-1',
        name_ar: 'حلويات',
        name_fr: 'Pâtisseries & Desserts',
        name_en: 'Sweets & Desserts',
        slug: 'sweets',
        image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80',
        recipe_count: 124,
    },
    {
        id: 'cat-2',
        name_ar: 'أطباق رئيسية',
        name_fr: 'Plats Principaux',
        name_en: 'Main Courses',
        slug: 'main-courses',
        image_url: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=400&q=80',
        recipe_count: 89,
    },
    {
        id: 'cat-3',
        name_ar: 'رمضان',
        name_fr: 'Spécial Ramadan',
        name_en: 'Ramadan Specials',
        slug: 'ramadan',
        image_url: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=400&q=80',
        recipe_count: 56,
    },
    {
        id: 'cat-4',
        name_ar: 'سلطات',
        name_fr: 'Salades & Entrées',
        name_en: 'Salads & Starters',
        slug: 'salads',
        image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
        recipe_count: 43,
    },
    {
        id: 'cat-5',
        name_ar: 'مملحات',
        name_fr: 'Salés & Feuilletés',
        name_en: 'Savory Pastries',
        slug: 'savory',
        image_url: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&q=80',
        recipe_count: 67,
    },
    {
        id: 'cat-6',
        name_ar: 'مشروبات',
        name_fr: 'Boissons & Smoothies',
        name_en: 'Drinks & Smoothies',
        slug: 'drinks',
        image_url: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&q=80',
        recipe_count: 31,
    },
    {
        id: 'cat-7',
        name_ar: 'خبز وعجائن',
        name_fr: 'Pains & Viennoiseries',
        name_en: 'Breads & Doughs',
        slug: 'breads',
        image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
        recipe_count: 38,
    },
    {
        id: 'cat-8',
        name_ar: 'أطباق مغربية',
        name_fr: 'Cuisine Marocaine',
        name_en: 'Moroccan Cuisine',
        slug: 'moroccan',
        image_url: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=400&q=80',
        recipe_count: 72,
    },
];

export const MOCK_RECIPES: Recipe[] = [
    {
        id: 'rec-1',
        title_ar: 'كعكة الشوكولاتة بالكريمة',
        title_fr: 'Gâteau Fondant au Chocolat et Crème',
        title_en: 'Creamy Chocolate Fudge Cake',
        slug: 'chocolate-cream-cake',
        description_ar: 'كعكة شوكولاتة غنية وهشة مع طبقة فاخرة من الكريمة والغاناش المخملي. وصفة مثالية للمناسبات والعزومات.',
        category_id: 'cat-1',
        category_name_ar: 'حلويات',
        difficulty: 'easy',
        prep_time_minutes: 20,
        cook_time_minutes: 45,
        servings: 8,
        main_image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
        video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        views_count: 18420,
        rating_avg: 4.9,
        rating_count: 2140,
        featured: true,
        published: true,
        created_at: '2026-06-15T10:00:00Z',
        ingredients: [
            { id: 'ing-1', item_ar: 'دقيق حلويات ممتاز', amount: '250g', order_index: 1 },
            { id: 'ing-2', item_ar: 'بودرة كاكاو خام مر', amount: '75g', order_index: 2 },
            { id: 'ing-3', item_ar: 'سكر ناعم', amount: '200g', order_index: 3 },
            { id: 'ing-4', item_ar: 'بيض طازج', amount: '3 حبات', order_index: 4 },
            { id: 'ing-5', item_ar: 'حليب دافئ', amount: '200ml', order_index: 5 },
            { id: 'ing-6', item_ar: 'زيت نباتي', amount: '100ml', order_index: 6 },
            { id: 'ing-7', item_ar: 'بيكنج بودر', amount: '1 كيس (11g)', order_index: 7 },
            { id: 'ing-8', item_ar: 'فانيلا سائلا', amount: '1 ملعقة صغيرة', order_index: 8 },
            { id: 'ing-9', item_ar: 'كريمة خفق للزينة', amount: '250ml', order_index: 9 }
        ],
        steps: [
            { id: 'st-1', step_number: 1, instruction_ar: 'في وعاء كبير، نخفق البيض والسكر والفانيلا جيداً حتى نحصل على خليط كريمي فاتح اللون.', image_url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&q=80' },
            { id: 'st-2', step_number: 2, instruction_ar: 'نضيف الزيت والحليب الدافئ بالتدريج مع الاستمرار في الخفق الخفيف.', image_url: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&q=80' },
            { id: 'st-3', step_number: 3, instruction_ar: 'ننخل الدقيق والكاكاو والبيكنج بودر فوق الخليط ونقلب برفق حتى يتجانس القوام.', image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80' },
            { id: 'st-4', step_number: 4, instruction_ar: 'نسكب الخليط في قالب مدهون بالزبداً ومبطن بالكاكاو، ونخبز في فرن مسخن مسبقاً على 180° مئوية لمدة 40-45 دقيقة.', image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80' },
            { id: 'st-5', step_number: 5, instruction_ar: 'نترك الكعكة تبرد تماماً ثم نغطيها بالكريمة المخفوقة وزينة الشوكولاتة المبشورة.' }
        ]
    },
    {
        id: 'rec-2',
        title_ar: 'طاجين الدجاج بالزيتون والليمون المصير',
        title_fr: 'Poulet aux Olives et Citron Confit',
        title_en: 'Moroccan Chicken Tagine with Olives & Preserved Lemon',
        slug: 'chicken-tagine-olives',
        description_ar: 'طبق مغربي أصيل وفاخر بنكهة متوازنة بين الدجاج الطري المحمر والزيتون الأخضر والليمون المخلل المصير. من أشهى الأطباق التقليدية في المناسبات والعائلات.',
        category_id: 'cat-8',
        category_name_ar: 'أطباق مغربية',
        difficulty: 'medium',
        prep_time_minutes: 30,
        cook_time_minutes: 60,
        servings: 6,
        main_image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=800&q=80',
        views_count: 24150,
        rating_avg: 4.9,
        rating_count: 1876,
        featured: true,
        published: true,
        created_at: '2026-06-18T14:30:00Z',
        ingredients: [
            { id: 'ing-20', item_ar: 'دجاجة كاملة منظفة ومقطعة', amount: '1 دجاجة (1.5 kg)', order_index: 1 },
            { id: 'ing-21', item_ar: 'بصل كبير مفروم ناعماً', amount: '2 بصلات', order_index: 2 },
            { id: 'ing-22', item_ar: 'ثوم مهروس', amount: '3 فصوص', order_index: 3 },
            { id: 'ing-23', item_ar: 'زيت زيتون أصلي', amount: '4 ملاعق كبيرة', order_index: 4 },
            { id: 'ing-24', item_ar: 'ليمونة جامدة مصيرة (مخللة)', amount: '1 ليمونة', order_index: 5 },
            { id: 'ing-25', item_ar: 'زيتون أخضر مغربي', amount: '200g', order_index: 6 },
            { id: 'ing-26', item_ar: 'توابل (زنجبيل، كركم، فلفل أسود، زعفران حر)', amount: '1 ملعقة صغيرة من كل نوع', order_index: 7 },
            { id: 'ing-27', item_ar: 'كزبرة وبقدونس مفرومان', amount: '3 ملاعق كبيرة', order_index: 8 },
            { id: 'ing-28', item_ar: 'سمن مغربي تقليدي', amount: '1 ملعقة صغيرة', order_index: 9 }
        ],
        steps: [
            { id: 'st-20', step_number: 1, instruction_ar: 'في قدر الطاجين أو القدر العميق، نخلط الثوم والتوابل والكزبرة والبقدونس والزعفران والسمن وقليل من الماء لتجهيز الشرمولة.', image_url: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=600&q=80' },
            { id: 'st-21', step_number: 2, instruction_ar: 'ننقع قطعات الدجاج في الشرمولة جيداً لمدة 20 دقيقة على الأقل لامتصاص النكهات الغنية.', image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80' },
            { id: 'st-22', step_number: 3, instruction_ar: 'نضع البصل المفروم في الطاجين مع زيت الزيتون، ونرص فوقه قطعة الدجاج ونتركه يتقلى على نار هادئة.', image_url: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&q=80' },
            { id: 'st-23', step_number: 4, instruction_ar: 'نضيف قشر الليمون المصير المقطع وشريحة من اللب مع نصف كوب ماء دافئ، ونغطي الطاجين لمدة 45 دقيقة.', image_url: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=600&q=80' },
            { id: 'st-24', step_number: 5, instruction_ar: 'قبل النضج بـ 15 دقيقة، نضيف الزيتون الأخضر ونترك المرق يختثر ويثقل. يقدم ساخناً مع الخبز المغربي الطازج.' }
        ]
    },
    {
        id: 'rec-3',
        title_ar: 'بريوات اللوز والعسل',
        title_fr: 'Briouates aux Amandes et Miel',
        title_en: 'Crispy Almond & Honey Briouats',
        slug: 'almond-honey-briouats',
        description_ar: 'مثلثات الورقة المقرمشة المحشوة بعقدة اللوز المعطرة بماء الزهر والقرفة، والمغشاة بالعسل الحر الطبيعي.',
        category_id: 'cat-1',
        category_name_ar: 'حلويات',
        difficulty: 'medium',
        prep_time_minutes: 40,
        cook_time_minutes: 20,
        servings: 12,
        main_image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&q=80',
        views_count: 12300,
        rating_avg: 4.8,
        rating_count: 965,
        featured: true,
        published: true,
        created_at: '2026-06-20T11:00:00Z',
        ingredients: [
            { id: 'ing-30', item_ar: 'ورقة البسطيلة الطازجة', amount: '500g', order_index: 1 },
            { id: 'ing-31', item_ar: 'لوز مفسوخ ومطحون ناعماً', amount: '500g', order_index: 2 },
            { id: 'ing-32', item_ar: 'سكر ناعم', amount: '150g', order_index: 3 },
            { id: 'ing-33', item_ar: 'ماء زهر حر', amount: '3 ملاعق كبيرة', order_index: 4 },
            { id: 'ing-34', item_ar: 'قرفة ناعمة', amount: '1 ملعقة صغيرة', order_index: 5 },
            { id: 'ing-35', item_ar: 'زبدة مذابة', amount: '100g', order_index: 6 },
            { id: 'ing-36', item_ar: 'عسل حر دافئ للتسلية', amount: '500g', order_index: 7 }
        ],
        steps: [
            { id: 'st-30', step_number: 1, instruction_ar: 'نخلط اللوز المطحون مع السكر والقرفة وماء الزهر والزبدة ونعجن حتى تتكون عقدة لينة متماسكة.' },
            { id: 'st-31', step_number: 2, instruction_ar: 'نشكل عقدة اللوز إلى كرات صغيرة متساوية الحجم.' },
            { id: 'st-32', step_number: 3, instruction_ar: 'نقطع ورقة البسطيلة إلى أشرطة طويلة، نضع كرة اللوز في البداية ونلف على شكل مثلث متناسق.' },
            { id: 'st-33', step_number: 4, instruction_ar: 'نغلق الطرف بخليط دقيق وماء، ونقلي البريوات في زيت ساخن أو نخبزها في الفرن حتى تتحمر.' },
            { id: 'st-34', step_number: 5, instruction_ar: 'نغمط البريوات فور خروجها ساخنة في العسل الدافئ ونتركها تتشرب العسل ثم نزيّنها بالسمسم.' }
        ]
    },
    {
        id: 'rec-4',
        title_ar: 'كسكس مغربي بالخضروات السبع',
        title_fr: 'Couscous Marocain aux Sept Légumes',
        title_en: 'Traditional Moroccan Seven Vegetable Couscous',
        slug: 'moroccan-vegetable-couscous',
        description_ar: 'ملك المائدة المغربية في يوم الجمعة والمناسبات. كسكس مبخر ثلاث مرات فوق مرق اللحم اللذيذ والخضار الطازجة.',
        category_id: 'cat-8',
        category_name_ar: 'أطباق مغربية',
        difficulty: 'easy',
        prep_time_minutes: 35,
        cook_time_minutes: 75,
        servings: 8,
        main_image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=800&q=80',
        views_count: 41200,
        rating_avg: 5.0,
        rating_count: 3204,
        featured: true,
        published: true,
        created_at: '2026-06-22T09:15:00Z',
        ingredients: [
            { id: 'ing-40', item_ar: 'كسكس متوسط الجودة', amount: '1 kg', order_index: 1 },
            { id: 'ing-41', item_ar: 'لحم غنمي أو بقر طازج', amount: '1 kg', order_index: 2 },
            { id: 'ing-42', item_ar: 'خضروات مشكلة (قرع أحمر، جزر، لفت، كرفس، ملفوف، حمص، قرع أخضر)', amount: '1.5 kg', order_index: 3 },
            { id: 'ing-43', item_ar: 'بصل وثوم وطماطم مفرومة', amount: '2 بصلات + 2 طماطم', order_index: 4 },
            { id: 'ing-44', item_ar: 'سمن مغربي وزيت زيتون', amount: '2 ملعقة كبيرة', order_index: 5 }
        ],
        steps: [
            { id: 'st-40', step_number: 1, instruction_ar: 'في قدر البرمة السفلي، نقلي اللحم مع البصل والطماطم والتوابل وزيت الزيتون والسمن.' },
            { id: 'st-41', step_number: 2, instruction_ar: 'نبلل الكسكس بالقليل من الماء والزيت، ونضعه في الكسكاس ليتسلق فوق مرق اللحم.' },
            { id: 'st-42', step_number: 3, instruction_ar: 'نكرر عملية التبخير 3 مرات مع رش الكسكس بالماء المملح والدهن بالسمن في كل التبخيرة.' },
            { id: 'st-43', step_number: 4, instruction_ar: 'نضيف الخضروات بالتدريج حسب درجة نضجها في المرق.' },
            { id: 'st-44', step_number: 5, instruction_ar: 'نسقي الكسكس في القصرية التقليدية ونرص اللحم والخضروات بشكل أنيق ونقدم المرق جانباً.' }
        ]
    },
    {
        id: 'rec-5',
        title_ar: 'شباكية العيد المعسلة',
        title_fr: 'Chebakia Traditionnelle au Miel',
        title_en: 'Authentic Honey Chebakia Pastry',
        slug: 'authentic-honey-chebakia',
        description_ar: 'حلوى الشباكية المغربية التقليدية برائحة النافع وحبة حلاوة والماء زهر، معسلة ومقرمشة تذوب في الفم.',
        category_id: 'cat-3',
        category_name_ar: 'رمضان',
        difficulty: 'medium',
        prep_time_minutes: 60,
        cook_time_minutes: 40,
        servings: 15,
        main_image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
        views_count: 58400,
        rating_avg: 4.9,
        rating_count: 4521,
        featured: true,
        published: true,
        created_at: '2026-06-25T16:00:00Z',
        ingredients: [
            { id: 'ing-50', item_ar: 'دقيق أبيض ممتاز', amount: '1 kg', order_index: 1 },
            { id: 'ing-51', item_ar: 'سمسم محمص ومطحون ناعماً', amount: '200g', order_index: 2 },
            { id: 'ing-52', item_ar: 'لوز محمص ومطحون بالقشرة', amount: '100g', order_index: 3 },
            { id: 'ing-53', item_ar: 'نافع وحبة حلاوة وقرفة مطحونة', amount: '2 ملعقة كبيرة', order_index: 4 },
            { id: 'ing-54', item_ar: 'ماء زهر حر مع زعفران', amount: '1 كوب', order_index: 5 }
        ],
        steps: [
            { id: 'st-50', step_number: 1, instruction_ar: 'نخلط جميع المكونات الجافة جيداً، ثم نضيف الزبدة والزيت وماء الزهر والخل حتى تتكون عجينة متماسكة.' },
            { id: 'st-51', step_number: 2, instruction_ar: 'ندلك العجينة وتقسم إلى كرات ونورقها بالمدلاك ثم نقطعها بالجرارة الخاصة بالشباكية.' },
            { id: 'st-52', step_number: 3, instruction_ar: 'نشكل الأشرطة إلى وردات الشباكية التقليدية بمهارة.' },
            { id: 'st-53', step_number: 4, instruction_ar: 'نقلي في زيت غزير حتى تصبح ذهبية اللون ثم نطفئها فوراً في العسل الثقيل.' }
        ]
    },
    {
        id: 'rec-6',
        title_ar: 'سموثي الفراولة والموز المنعش',
        title_fr: 'Smoothie Fraise et Banane',
        title_en: 'Fresh Strawberry Banana Smoothie',
        slug: 'strawberry-banana-smoothie',
        description_ar: 'مشروب منعش وصحي غني بالفيتامينات، محضر بالفراولة الطازجة والموز والحليب مع لمسة عسل طبيعي.',
        category_id: 'cat-6',
        category_name_ar: 'مشروبات',
        difficulty: 'easy',
        prep_time_minutes: 5,
        cook_time_minutes: 0,
        servings: 2,
        main_image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80',
        views_count: 9800,
        rating_avg: 4.7,
        rating_count: 821,
        featured: false,
        published: true,
        created_at: '2026-06-28T08:00:00Z',
        ingredients: [
            { id: 'ing-60', item_ar: 'فراولة طازجة مجمدة', amount: '200g', order_index: 1 },
            { id: 'ing-61', item_ar: 'موز ناضج', amount: '2 حبات', order_index: 2 },
            { id: 'ing-62', item_ar: 'حليب كامل الدسم أو لبن زبادي', amount: '300ml', order_index: 3 },
            { id: 'ing-63', item_ar: 'عسل حر طبيعي', amount: '2 ملعقة كبيرة', order_index: 4 }
        ],
        steps: [
            { id: 'st-60', step_number: 1, instruction_ar: 'نضع جميع المكونات في الخلاط الكهربائي.' },
            { id: 'st-61', step_number: 2, instruction_ar: 'نخلط على سرعة عالية لمدة 2 دقيقة حتى نحصل على قوام مخملي متجانس.' },
            { id: 'st-62', step_number: 3, instruction_ar: 'يسكب في كؤوس التقديم الباردة ويزين بشرائح الفراولة والنعناع الطازج.' }
        ]
    }
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 'prod-1',
        title_ar: 'كتاب حلويات العيد - الشيف نور',
        title_fr: 'Livre Spécial Pâtisseries de l’Aïd',
        title_en: 'Chef Nour’s Eid Sweets Cookbook',
        slug: 'eid-sweets-cookbook',
        description_ar: 'دليلك الشامل لنجاح حلويات العيد والمناسبات بخطوات مبسطة ومقادير مضبوطة 100%. يضم 30 وصفة حصرياً مع أسرار الشيف نور الخاصة للحصول على نتائج احترافية من المرة الأولى.',
        price_mad: 49,
        old_price_mad: 99,
        discount_percent: 50,
        cover_image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
        file_url: '/assets/ebooks/chef-nour-eid-sweets.pdf',
        recipes_count: 30,
        features: [
            '30 وصفة مجربة ومكتوبة بدقة',
            'مقادير مضبوطة بالغرام والكوب',
            'أسرار الشيف لنضج مثالي وقرمشة تدوم',
            'صور عالية الدقة لكل مرحلة',
            'تحديثات مجانية مدى الحياة',
            'ضمان استرجاع لمدة 30 يوم'
        ],
        published: true,
        created_at: '2026-05-01T00:00:00Z',
    }
];

export const MOCK_REVIEWS: Review[] = [
    {
        id: 'rev-1',
        user_id: 'user-101',
        user_name: 'أم كريمة',
        user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80',
        recipe_id: 'rec-5',
        recipe_title_ar: 'شباكية العيد المعسلة',
        rating: 5,
        comment: 'جربت وصفة الشباكية وطلعت روعة! شكراً يا شيف نور، هشيشة ومعسلة كلها في نصف ساعة 👌',
        photo_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80',
        chef_reply: 'بالصحة والعافية اختي أم كريمة! يسعدني جداً نجاح الوصفة معك ❤️',
        likes_count: 47,
        moderation_status: 'approved',
        created_at: '2026-07-02T12:00:00Z',
    },
    {
        id: 'rev-2',
        user_id: 'user-102',
        user_name: 'ياسمينة ب.',
        user_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&q=80',
        recipe_id: 'rec-4',
        recipe_title_ar: 'كسكس مغربي بالخضروات',
        rating: 5,
        comment: 'الكسكس طلع لديد بزاف من عند ماما والطريقة واضحة جداً وسهلة التطبيق.',
        photo_url: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=500&q=80',
        likes_count: 93,
        moderation_status: 'approved',
        created_at: '2026-07-05T15:30:00Z',
    },
    {
        id: 'rev-3',
        user_id: 'user-103',
        user_name: 'حنان م.',
        user_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&q=80',
        recipe_id: 'rec-2',
        recipe_title_ar: 'طاجين الدجاج بالزيتون',
        rating: 5,
        comment: 'طاجين الدجاج كان لديد جداً! زدت شوية بهارات حسب ذوقي، شكراً شيف 🙏',
        photo_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&q=80',
        likes_count: 28,
        moderation_status: 'approved',
        created_at: '2026-07-10T18:20:00Z',
    },
    {
        id: 'rev-4',
        user_id: 'user-104',
        user_name: 'سعاد أ.',
        user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
        recipe_id: 'rec-3',
        recipe_title_ar: 'بريوات اللوز والعسل',
        rating: 5,
        comment: 'وصفة مقرمشة ولذيذة جداً. العسل واللوز بنكهة ماء الزهر خرافية!',
        photo_url: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500&q=80',
        likes_count: 14,
        moderation_status: 'pending',
        created_at: '2026-07-22T09:10:00Z',
    }
];

export const MOCK_ADMIN_STATS = {
    total_recipes: 487,
    total_recipes_change: '+5.7%',
    book_sales: 1248,
    book_sales_change: '+15.4%',
    pending_reviews: 156,
    pending_reviews_change: '+8.2%',
    total_views: '3.2M',
    total_views_change: '+12.5%',
};

export const MOCK_USER_PROFILE: UserProfile = {
    id: 'usr-admin',
    full_name: 'الشيف نور',
    email: 'chefnour@example.com',
    avatar_url: '/chef-nour.jpg',
    role: 'admin',
    created_at: '2025-01-01T00:00:00Z',
};
