import { Category, Recipe, Product, Review, UserProfile } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
    {
        id: 'cat-1',
        name_ar: 'حلويات',
        name_fr: 'Pâtisseries & Desserts',
        name_en: 'Sweets & Desserts',
        slug: 'sweets',
        image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-2',
        name_ar: 'أطباق رئيسية',
        name_fr: 'Plats Principaux',
        name_en: 'Main Courses',
        slug: 'main-courses',
        image_url: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-3',
        name_ar: 'رمضان',
        name_fr: 'Spécial Ramadan',
        name_en: 'Ramadan Specials',
        slug: 'ramadan',
        image_url: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-4',
        name_ar: 'سلطات',
        name_fr: 'Salades & Entrées',
        name_en: 'Salads & Starters',
        slug: 'salads',
        image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-5',
        name_ar: 'مملحات',
        name_fr: 'Salés & Feuilletés',
        name_en: 'Savory Pastries',
        slug: 'savory',
        image_url: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-6',
        name_ar: 'مشروبات',
        name_fr: 'Boissons & Smoothies',
        name_en: 'Drinks & Smoothies',
        slug: 'drinks',
        image_url: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-7',
        name_ar: 'خبز وعجائن',
        name_fr: 'Pains & Viennoiseries',
        name_en: 'Breads & Doughs',
        slug: 'breads',
        image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
        recipe_count: 0,
    },
    {
        id: 'cat-8',
        name_ar: 'أطباق مغربية',
        name_fr: 'Cuisine Marocaine',
        name_en: 'Moroccan Cuisine',
        slug: 'moroccan',
        image_url: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=400&q=80',
        recipe_count: 0,
    },
];

export const MOCK_RECIPES: Recipe[] = [
    {
        id: 'rec-1',
        title_ar: 'الحريرة المغربية الأصيلة لرمضان',
        title_fr: 'Harira Marocaine Authentique',
        title_en: 'Authentic Moroccan Harira Soup',
        slug: 'harira-marocaine-authentique',
        description_ar: 'الحريرة المغربية التقليدية بمقادير مضبوطة، طعم غني ومغذي مثالي لمائدة الإفطار في شهر رمضان المبارك.',
        description_fr: 'La soupe marocaine traditionnelle indispensable sur la table du Ramadan.',
        description_en: 'Traditional Moroccan soup essential for Ramadan Iftar meals.',
        category_id: 'cat-3',
        category_name_ar: 'رمضان',
        prep_time_minutes: 25,
        cook_time_minutes: 50,
        servings: 6,
        difficulty: 'medium',
        main_image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
        gallery_images: [],
        video_url: '',
        published: true,
        rating_avg: 4.9,
        rating_count: 38,
        views_count: 1420,
        created_at: new Date().toISOString(),
        ingredients: [
            { id: 'ing-1', item_ar: 'حمص منقوع ومقشر', item_fr: 'Pois chiches', item_en: 'Chickpeas', amount: '1 كأس', order_index: 1 },
            { id: 'ing-2', item_ar: 'عدس مغسول', item_fr: 'Lentilles', item_en: 'Lentils', amount: '0.5 كأس', order_index: 2 },
            { id: 'ing-3', item_ar: 'طماطم مفرومة طازجة', item_fr: 'Tomates fraîches', item_en: 'Fresh tomatoes', amount: '500 غرام', order_index: 3 },
            { id: 'ing-4', item_ar: 'قطع لحم مكعبات', item_fr: 'Viande en dés', item_en: 'Diced meat', amount: '200 غرام', order_index: 4 },
            { id: 'ing-5', item_ar: 'كزبرة وبقدونس وكرفس', item_fr: 'Coriandre, persil, céleri', item_en: 'Cilantro, parsley, celery', amount: '1 حزمة', order_index: 5 },
            { id: 'ing-6', item_ar: 'دقيق لتدوير الحريرة', item_fr: 'Farine', item_en: 'Flour', amount: '4 معالق كبار', order_index: 6 },
        ],
        steps: [
            { id: 'st-1', step_number: 1, instruction_ar: 'في طنجرة الضغط، نضع اللحم مع الحمص، العدس، البصل المفروم والبهارات (كركم، سكنجبير، إبزار، ملح، سمن) ومعلقة زيت.' },
            { id: 'st-2', step_number: 2, instruction_ar: 'نضيف الأعشاب المفرومة (كزبرة وبقدونس وكرفس) والماء الغالي، ونغلق الطنجرة لمدة 35 دقيقة حتى ينضج الحمص واللحم.' },
            { id: 'st-3', step_number: 3, instruction_ar: 'نضيف مطحون الطماطم ثم نخلط الدقيق بالماء ونضيفه تدريجياً مع التحرّك المستمر حتى تتكاثف الحريرة وتطهى التدويرة.' },
        ],
    },
    {
        id: 'rec-2',
        title_ar: 'الشباكية المغربية المجدولة بالعسل',
        title_fr: 'Chebakia Marocaine au Miel',
        title_en: 'Moroccan Honey Chebakia',
        slug: 'chebakia-marocaine-au-miel',
        description_ar: 'شباكية معلكة وشاربة العسل بمقادير دقيقة وطريقة تشبيك سهلة ومبسطة للجميع.',
        description_fr: 'Pâtisserie marocaine au miel et sésame pour le Ramadan.',
        description_en: 'Moroccan honey and sesame pastry for Ramadan.',
        category_id: 'cat-3',
        category_name_ar: 'رمضان',
        prep_time_minutes: 40,
        cook_time_minutes: 30,
        servings: 10,
        difficulty: 'medium',
        main_image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
        gallery_images: [],
        video_url: '',
        published: true,
        rating_avg: 5.0,
        rating_count: 52,
        views_count: 2150,
        created_at: new Date().toISOString(),
        ingredients: [
            { id: 'ing-7', item_ar: 'دقيق أبيض ممتاز', item_fr: 'Farine', item_en: 'Flour', amount: '1 كيلوغرام', order_index: 1 },
            { id: 'ing-8', item_ar: 'زنجلان (سمسم) مطحون', item_fr: 'Sésame moulu', item_en: 'Ground sesame', amount: '1 كأس', order_index: 2 },
            { id: 'ing-9', item_ar: 'عسل حر للتعسيل', item_fr: 'Miel', item_en: 'Honey', amount: '1 كيلوغرام', order_index: 3 },
        ],
        steps: [
            { id: 'st-4', step_number: 1, instruction_ar: 'نخلط النواشف ثم نضيف الزبدة والزيت والماء زهر المذوب فيه الزعفران، ونعجن عجيناً متماسكاً.' },
            { id: 'st-5', step_number: 2, instruction_ar: 'نورّق العجين ونقطعه بالجرارة ونشَبّك الحبات، ثم نقليها في زيت ساخن ونغمرها فوراً في العسل البارد.' },
        ],
    },
    {
        id: 'rec-3',
        title_ar: 'طجين اللحم بالبرقوق والمشمش المجفف',
        title_fr: 'Tajine d\'Agneau aux Pruneaux',
        title_en: 'Moroccan Lamb Tajine with Prunes',
        slug: 'tajine-agneau-aux-pruneaux',
        description_ar: 'طجين مغربي فاخر باللحم المحمر والبرقوق المعسل بالقرفة وماء الزهر، طبق الأعراس والمناسبات.',
        description_fr: 'Tajine d\'agneau traditionnel aux pruneaux et amandes.',
        description_en: 'Traditional Moroccan lamb tajine with caramelized prunes.',
        category_id: 'cat-8',
        category_name_ar: 'أطباق مغربية',
        prep_time_minutes: 20,
        cook_time_minutes: 75,
        servings: 4,
        difficulty: 'easy',
        main_image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14da?w=800&q=80',
        gallery_images: [],
        video_url: '',
        published: true,
        rating_avg: 4.8,
        rating_count: 29,
        views_count: 1890,
        created_at: new Date().toISOString(),
        ingredients: [
            { id: 'ing-10', item_ar: 'لحم غنم أو بقر', item_fr: 'Viande d\'agneau', item_en: 'Lamb meat', amount: '1 كيلوغرام', order_index: 1 },
            { id: 'ing-11', item_ar: 'برقوق مجفف معسل', item_fr: 'Pruneaux', item_en: 'Prunes', amount: '250 غرام', order_index: 2 },
        ],
        steps: [
            { id: 'st-6', step_number: 1, instruction_ar: 'نقلّي اللحم مع البصل والتوابل والزعفران الحر والسمن، ثم نضيف الماء ونتركه يطهى على نار هادئة.' },
        ],
    },
    {
        id: 'rec-4',
        title_ar: 'البطبوط المغربي المنفوش والمحشو',
        title_fr: 'Batbout Marocain Farci',
        title_en: 'Moroccan Stuffed Batbout Bread',
        slug: 'batbout-marocain-farci',
        description_ar: 'بطبوط مغربي خفيف ومجوف من الداخل، مثالي للحشوات السريعة والمقبلات الرمضانية.',
        description_fr: 'Pains batbout moelleux farcis pour le Ramadan.',
        description_en: 'Fluffy Moroccan flatbreads perfect for stuffing.',
        category_id: 'cat-5',
        category_name_ar: 'مملحات',
        prep_time_minutes: 20,
        cook_time_minutes: 15,
        servings: 8,
        difficulty: 'easy',
        main_image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&q=80',
        gallery_images: [],
        video_url: '',
        published: true,
        rating_avg: 4.7,
        rating_count: 19,
        views_count: 980,
        created_at: new Date().toISOString(),
        ingredients: [
            { id: 'ing-12', item_ar: 'دقيق فينو ودقيق أبيض', item_fr: 'Farine & Semoule fine', item_en: 'Flour & Fine semolina', amount: '500 غرام', order_index: 1 },
        ],
        steps: [
            { id: 'st-7', step_number: 1, instruction_ar: 'نعجن العجين ونتركه يرتاح، ثم نبسط ونقطع دوائر ونطهى على مقلاة ثقيلة ساخنة مع التقليب المباشر ليينتفخ.' },
        ],
    }
];

// ─── PRODUCTS (Digital Ebooks) ────────────────────────────────────────────────
export const MOCK_PRODUCTS: Product[] = [
    {
        id: 'prod-1',
        title_ar: 'كتاب حلويات العيد - الشيف نور',
        title_fr: "Livre Spécial Pâtisseries de l'Aïd",
        title_en: "Chef Nour's Eid Sweets Cookbook",
        slug: 'eid-sweets-cookbook',
        description_ar: 'دليلك الشامل لنجاح حلويات العيد والمناسبات بخطوات مبسطة ومقادير مضبوطة 100%. يضم 30 وصفة حصرياً مع أسرار الشيف نور الخاصة للحصول على نتائج احترافية من المرة الأولى.',
        price_mad: 49,
        old_price_mad: 99,
        discount_percent: 50,
        cover_image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
        file_url: '/assets/ebooks/chef-nour-eid-sweets.pdf',
        recipes_count: 30,
        features: [
            '30 وصفة مجربة ومكتوبة بدقة',
            'مقادير مضبوطة بالغرام والكوب',
            'أسرار الشيف لنضج مثالي وقرمشة تدوم',
            'صور عالية الدقة لكل مرحلة',
            'تحديثات مجانية مدى الحياة',
            'ضمان استرجاع لمدة 30 يوم'
        ],
        published: true,
        created_at: '2026-05-01T00:00:00Z',
    }
];

// ─── REVIEWS: Start empty — real reviews come from Supabase ───────────────────
export const MOCK_REVIEWS: Review[] = [];

// ─── ADMIN STATS: Real starting values ────────────────────────────────────────
export const MOCK_ADMIN_STATS = {
    total_recipes: 0,
    total_recipes_change: '+0%',
    book_sales: 0,
    book_sales_change: '+0%',
    pending_reviews: 0,
    pending_reviews_change: '+0%',
    total_views: '0',
    total_views_change: '+0%',
};

// ─── DEFAULT USER: Admin Chef Nour ────────────────────────────────────────────
export const MOCK_USER_PROFILE: UserProfile = {
    id: 'usr-admin',
    full_name: 'الشيف نور',
    email: 'chefnour@example.com',
    avatar_url: '/chef-nour.jpg',
    role: 'admin',
    created_at: '2025-01-01T00:00:00Z',
};
